basePath: /
info:
  contact:
    name: '@vsoch'
    url: https://github.com/buildsi/drift-server/issues
  description: Record metadata about inflection point changes in packages
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Drift Server API
  version: "1.0"
paths:
  /:
    get:
      description: get server info
      operationId: get-server-info
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get server info
  /build/:
    post:
      consumes:
      - application/json
      description: create a new build
      operationId: post-build
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create a new build
  /builds/:
    get:
      consumes:
      - application/json
      description: List builds
      operationId: get-builds
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all builds
  /commits/:
    get:
      consumes:
      - application/json
      description: List commits
      operationId: get-commits
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all commits
  /inflection-point/:
    post:
      consumes:
      - application/json
      description: created a new inflection point
      operationId: post-inflection-point
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create a new inflection point
  /inflection-points/:
    get:
      consumes:
      - application/json
      description: List all inflectoin points
      operationId: get-inflection-points
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all inflection points
  /packages/:
    get:
      consumes:
      - application/json
      description: List packages
      operationId: get-packages
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all packages
  /spec/:
    post:
      consumes:
      - application/json
      description: create a new package spec
      operationId: post-spec
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create a new package spec
  /specs/:
    get:
      consumes:
      - application/json
      description: List specs
      operationId: get-specs
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all specs
  /tags/:
    get:
      consumes:
      - application/json
      description: List tags
      operationId: get-tags
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: List all tags
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
