name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: deploy
        run: |
          git checkout gh-pages

          if [[ $(git restore --source main vis) == 0 ]]; then
            cp -r vis/* .
            rm -r vis/

            git config --global user.name "github-actions"
            git config --global user.email "github-actions@users.noreply.github.com"

            git add .
            git commit -m "gh-pages deploy ${date}"
            git push
          fi
