name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          fetch-depth: 0

      - name: deploy
        run: |
          git restore --source origin/${GITHUB_REF##*/} vis
          cp -r vis/* .
          rm -r vis/

          git add .
          git commit -m "gh-pages deploy ${date}"
          git push