name: Publish Container Image

on:
  push:
    branches:
      - main

jobs:
  run_analysis:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install Deps
        run: |
          cd ..
          git clone https://github.com/spack/spack.git
          git clone https://github.com/buildsi/helicase.git
          pip3 install -e helicase/
          cd drift-analysis

      - name: Run Analysis
        run: |
          time python3 drift.py spack/